/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_landleaf_serial_jni_SerialPortJNI */

#ifndef _Included_com_landleaf_serial_jni_SerialPortJNI
#define _Included_com_landleaf_serial_jni_SerialPortJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef com_landleaf_serial_jni_SerialPortJNI_RS485Read
#define com_landleaf_serial_jni_SerialPortJNI_RS485Read 0L
#undef com_landleaf_serial_jni_SerialPortJNI_RS485Write
#define com_landleaf_serial_jni_SerialPortJNI_RS485Write 1L
/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    setSpeed
 * Signature: (Ljava/io/FileDescriptor;I)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_setSpeed
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    setParity
 * Signature: (Ljava/io/FileDescriptor;III)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_setParity
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    openDev
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_openDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    open485Dev
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_open485Dev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    closeDev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_closeDev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    close485Dev
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_close485Dev
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    readBytes
 * Signature: (Ljava/io/FileDescriptor;[BII)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_readBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    writeBytes
 * Signature: (Ljava/io/FileDescriptor;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_writeBytes
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     com_landleaf_serial_jni_SerialPortJNI
 * Method:    set485mod
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_landleaf_serial_jni_SerialPortJNI_set485mod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
